name: Deploy JTL-Connector to Mittwald

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH script
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     p689712.mittwaldserver.info
          username: p689712
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     22
          script: |
            bash -l .github/deploy/deploy.sh
