name: Deploy JTL-Connector to Mittwald

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Deploy to Master"
        if: ${{ github.ref == 'refs/heads/master' }}
        run: /usr/bin/env bash ${GITHUB_WORKSPACE}/.github/deploy/deploy.sh
